import '@/components/Accordions/Accordions.makeswift'
import '@/components/AnimatedEyebrowText/AnimatedEyebrowText.makeswift'
import '@/components/Button/Button.makeswift'
import '@/components/Marquee/Marquee.makeswift'
import '@/components/Navigation/Navigation.makeswift'
import '@/components/Tabs/Tabs.makeswift'
import '@/components/TrophyStickyContainer/TrophyStickyContainer.makeswift'
