import { Winner } from './types'

const YEAR = '2026'

export const PAST_WINNERS: Winner[] = [
  {
    name: 'Kelsey Hightower',
    project: 'Kubernetes',
    category: 'lifetime-achievement',
    year: YEAR,
    image: { url: '/winners/kelsey-hightower.jpg' },
    imageAlt: 'Portrait of Kelsey Hightower',
    projectLink: { href: 'https://kubernetes.io' },
    linkedin: { href: 'https://www.linkedin.com/in/kelsey-hightower-849b342b1' },
  },
  {
    name: 'Model Context Protocol',
    category: 'commit-of-the-year',
    year: YEAR,
    image: { url: '/winners/model-context-protocol.png' },
    imageAlt: 'Model Context Protocol logo',
    projectLink: {
      href: 'https://modelcontextprotocol.io/docs/2026-07-28/getting-started/intro',
    },
    website: {
      href: 'https://modelcontextprotocol.io/docs/2026-07-28/getting-started/intro',
    },
  },
  {
    name: 'Anthony Fu',
    project: 'VueUse, Vitest, and UnoCSS',
    category: 'maintainer-of-the-year',
    year: YEAR,
    image: { url: '/winners/anthony-fu.jpg' },
    imageAlt: 'Portrait of Anthony Fu',
    projectLink: { href: 'https://github.com/antfu' },
    linkedin: { href: 'https://www.linkedin.com/in/antfu' },
    x: { href: 'https://x.com/antfu7' },
  },
  {
    name: 'goose',
    category: 'small-project-of-the-year',
    year: YEAR,
    image: { url: '/winners/goose.png' },
    imageAlt: 'goose logo',
    projectLink: { href: 'https://github.com/aaif-goose/goose' },
    linkedin: { href: 'https://www.linkedin.com/company/goose-oss' },
    x: { href: 'https://x.com/goose_oss' },
  },
  {
    name: 'TanStack Router',
    category: 'large-project-of-the-year',
    year: YEAR,
    image: { url: '/winners/tanstack.png' },
    imageAlt: 'TanStack logo',
    projectLink: { href: 'https://github.com/TanStack/router' },
    linkedin: { href: 'https://www.linkedin.com/company/tanstack' },
    x: { href: 'https://x.com/tan_stack' },
  },
  {
    name: 'Ben Gubler',
    project: 'Eta',
    category: 'rising-star-contributor',
    year: YEAR,
    image: { url: '/winners/ben-gubler.jpg' },
    imageAlt: 'Portrait of Ben Gubler',
    projectLink: { href: 'https://github.com/bgub/eta' },
    linkedin: { href: 'https://www.linkedin.com/in/ben-gubler/' },
    x: { href: 'https://x.com/bgub_' },
  },
  {
    name: 'React Email',
    category: 'documentation-design-excellence',
    year: YEAR,
    image: { url: '/winners/react-email.png' },
    imageAlt: 'React Email logo',
    projectLink: { href: 'https://react.email' },
    linkedin: { href: 'https://www.linkedin.com/company/resend' },
    x: { href: 'https://x.com/resend' },
  },
  {
    name: 'freeCodeCamp',
    category: 'open-source-for-good',
    year: YEAR,
    image: { url: '/winners/freecodecamp.jpg' },
    imageAlt: 'freeCodeCamp logo',
    projectLink: { href: 'https://www.freecodecamp.org/' },
    linkedin: { href: 'https://www.linkedin.com/school/free-code-camp' },
    x: { href: 'https://x.com/freeCodeCamp' },
  },
  {
    name: 'React Email',
    category: 'community-choice-award',
    year: YEAR,
    image: { url: '/winners/react-email.png' },
    imageAlt: 'React Email logo',
    projectLink: { href: 'https://react.email' },
    linkedin: { href: 'https://www.linkedin.com/company/resend' },
    x: { href: 'https://x.com/resend' },
  },
  {
    name: 'Chris Griffing',
    project: 'Open source',
    category: 'unsung-hero-award',
    year: YEAR,
    image: { url: '/winners/chris-griffing.jpg' },
    imageAlt: 'Portrait of Chris Griffing',
    projectLink: { href: 'https://github.com/cmgriffing' },
    linkedin: { href: 'https://www.linkedin.com/in/cmgriffing' },
    x: { href: 'https://x.com/cmgriffing' },
  },
]
